join:
  welcome: "Guten Tag" # Willkommensnachricht
  quit: "Bis bald" # Verabschiedungsnachricht
basic:
  servername: "HiyarCraft" # Servername steht vor jeder Befehlsnachricht wie auch Willkommens und Verabschiedungsnachricht
  maxhomes: 5 # Maximale Homes pro Spieler
warnsystem:
  tempban-duration: 86400 # Dauer des temporären Bans in Sekunden (Standard: 24 Stunden)

