### Plugin Name ###
name: lowdfx

### Build Version ###
version: '1.0'

### Main Class ###
main: at.lowdfx.lowdfx.LowdFX

### PaperAPI Version ###
api-version: '1.21'

### Autoren ###
authors:
  - LowdFX
  - MarcPG

### Soft-Dependencies für ProtocolEvents ###
dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: false
    ProtocolSupport:
      load: BEFORE
      required: false
    ViaVersion:
      load: BEFORE
      required: false
    ViaBackwards:
      load: BEFORE
      required: false
    ViaRewind:
      load: BEFORE
      required: false
    Geyser-Spigot:
      load: BEFORE
      required: false